# site settings
title: 경희가족한의원
subtitle: 대전 관평동 한의원
email: khfamilylove@naver.com
description: 대전 관평동 경희가족한의원 홈페이지
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: 주인장
street_address: 대전광역시 유성구 관평동 910 
city: 대전광역시
state: 대전광역시
zip_code: 34019
country: 대한민국
phone: (042)721-1075 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Kakao: 경희가족한의원
  Naver: https://m.place.naver.com/hospital/1422924794
  Blog: https://blog.naver.com/khfamilylove
  modoo: https://khfamily.modoo.at/?link=f4qlg1w3
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
